# Generated by Django 3.2.6 on 2021-10-01 18:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('tamano', models.CharField(max_length=4)),
                ('principal', models.BooleanField(default=False)),
                ('destacado', models.BooleanField(default=False)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocio.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('fecha', models.TimeField(verbose_name=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocio.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('aprecio', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('afecha', models.TimeField(verbose_name=django.utils.timezone.now)),
                ('aitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocio.producto')),
            ],
        ),
    ]
