# Generated by Django 3.2.6 on 2021-10-17 21:43

from django.db import migrations, models
import django.forms.widgets


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_auto_20211017_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name=django.forms.widgets.HiddenInput),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name=django.forms.widgets.HiddenInput),
        ),
    ]
